### ISSUE TITLE
Standard object.h and string.h

### ISSUE THREAD

**Issue by ZhichaoC** [kylesferrazza/swdev-a1-p2#2]
Can we have standard object.h and string.h to make our life easier across three data structures?
[suggested data type.zip](https://github.com/kylesferrazza/swdev-a1-p2/files/4119140/suggested.data.type.zip)

**Comment by kylesferrazza** [comment]
Looks like the link you provided has empty method bodies. We used the `string.h` and `object.h` given by instructors in [@166](https://piazza.com/class/k51bluky59n2jr?cid=166), with two additions to `String`, which can be removed if necessary.

Please let me know what you think is missing/wrong with `object.h` and `string.h`.

**Comment by ZhichaoC** [comment]
I think we be given only api and no code.

**Comment by kylesferrazza** [comment]
We have removed the implementations of `String` and `Object`.

**Comment by ZhichaoC** [comment]
Thanks
