### ISSUE TITLE
StrQueue should be included or not?

### ISSUE THREAD

**Issue by ZhichaoC** [kylesferrazza/swdev-a1-p2#3]
I believe you should only give Queue class and not StrQueue class according to the assignment description.

**Comment by kylesferrazza** [comment]
The assignment states:

> your design should accommodate at least Queues of Object and String

If we only had a `Queue` that supported `Object *`, how would you pop a `String *` out of the `Queue` without casting?

**Comment by ZhichaoC** [comment]
Isn't string an object?

**Comment by kylesferrazza** [comment]
`String` extends `Object`.

So, you would be able to put `String *`s into the regular `Queue`, but then only `pop` them as `Object *`s, which would make it hard to use as a `Queue` of `String`s without a lot of casting.

See the following posts on Piazza:

- [@320](https://piazza.com/class/k51bluky59n2jr?cid=320)
- [@319](https://piazza.com/class/k51bluky59n2jr?cid=319)

**Comment by ZhichaoC** [comment]
Cool, thanks
