### ISSUE TITLE
Queue push and peek

### ISSUE THREAD

**Issue by ZhichaoC** [kylesferrazza/swdev-a1-p2#5]
Queue is first in first out.

In test 1, we push "hello", then push "world", we expect to pop to return "hello", so does peek, but the test saying that peek should return "world".

Is that intentional?

**Comment by ConnorMullaly** [comment]
You are correct.  I will fix the incorrect tests.

**Comment by ZhichaoC** [comment]
Another minor detail, push_front and peek_end is little counter-intuitive. In queue we probably want push back and peek front.

**Comment by ConnorMullaly** [comment]
I can just change the API methods to be called push, pop, and peek so that you can decide which way you decide to implement the line

**Comment by ConnorMullaly** [comment]
Just committed test fixes and renaming of push, pop, and peek.
